### ISSUE TITLE
trigger link to open menu

### ISSUE THREAD

**Issue by sentisoft** [adgsm/multi-level-push-menu#100]
Hi,

Is there option to create trigger menu like this http://prntscr.com/6tq6gm.. on this page http://tympanus.net/Development/MultiLevelPushMenu/index2.html .. 

Regards,
Davor

**Comment by adgsm** [comment]
ima

pogledaj #5 i #25

**Comment by sentisoft** [comment]
svaka cast zemljak :)

**Comment by sentisoft** [comment]
just one more question.. I try to change this part http://prntscr.com/6txmm9 .. want to remove "All Categories" .. and first will be "Devices" but with this code http://prntscr.com/6txmup .. menu expand but not want to collapse .. I am not sure what I doing wrong...
