### ISSUE TITLE
Is there a way to know if the link is GroupItem or Not?

### ISSUE THREAD

**Issue by tsarma** [adgsm/multi-level-push-menu#101]
For group items you can use onGroupItemClick callback. But is there any way to know if its a group item or not so that I can (add Symbol / Change Text / Style) it.
Thanks for the script

**Comment by adgsm** [comment]
Hi, group item is item containing sub-items. Otherwise you can search for dom elements containing defined groupIcon css class (default set is "fa fa-angle-left"), so something like as follows
```javascript
$( '.levelHolderClass ' ).find( 'i.fa-angle-left' )
```
should give you back all group items.

**Comment by tsarma** [comment]
Ok Thank you. With that solved half problem. Is there a way to disable menu expand from obGroupItemClick callback. 

I want to expand only if event.target is 'i.fa-angle-left', not the link text. When click on link text I wanted to follow the link instead of expanding the menu.

**Comment by adgsm** [comment]
I guess issue #9 is what you're looking for...

**Comment by tsarma** [comment]
Yes, but!!
> "Thereafter alter jQuery.multilevelpushmenu.js as follows."

I don't want to alter the original script.

Right now I doing it so and it worked.
```javascript
                        onGroupItemClick : function(){

                            var event = arguments[0],
                            $item = arguments[2];
                            $i = $item.find( 'i:first');

                            if(event.target !== $i[0]) {
                                var itemHref = $item.find( 'a:first' ).attr( 'href' );
                                location.href = itemHref;
                            }

                        }
```
