### ISSUE TITLE
Activating menu links?

### ISSUE THREAD

**Issue by WriterStat** [adgsm/multi-level-push-menu#102]
There should probably be a tutorial on how all the different ways of activating links in the menu work.

For folks new?  Cuz I'm using the js array version for the menu items.  And I thought it would be as easy as just dropping in an href in the js array for that menu item and well clicking on it would take you there.  However giving the menu item an href in the js array, just displays that it should go there, doesn't actually innately go there.  Hahaha...

{
      name: 'Super Smart Phone',
      link: '#'
}

Shouldn't it?

I guess I could monitor the item click event, and check to see which one is clicking etc...  But wouldn't it be nicer if when you place an href in the js array for the menu it would go there?

What am I missing here?  Thx!  And thanks for a cool menu system.  I'm probably just missing something.  I'll try a few more things.

Best,

-C

**Comment by adgsm** [comment]
Hi, take a look at http://multi-level-push-menu.make.rs/#options

```
preventItemClick: true,                                    // set to false if you do not need event callback functionality
```

If you need click callback take a look at http://multi-level-push-menu.make.rs/#events

Regards

**Comment by WriterStat** [comment]
Hah!  Much thanks!  Would never have thought to look in options.  So basically I can have either an event or a pass through to the link/href.

Is there a way to have both?

Thanks!  Hopefully you'll get a chance to take a peek at what I create with this.

Cheers,

-C

**Comment by adgsm** [comment]
When click event is not prevented there is possibly no time for callback...
I suggest using callback following the example given bellow.

```
$( '#menu' ).multilevelpushmenu({
    onItemClick: function() {
        // First argument is original event object
        var event = arguments[0],
            // Second argument is menu level object containing clicked item (<div> element)
            $menuLevelHolder = arguments[1],
            // Third argument is clicked item (<li> element)
            $item = arguments[2],
            // Fourth argument is instance settings/options object
            options = arguments[3];

        // You can do some cool stuff here before
        // redirecting to href location
        // like logging the event or even
        // adding some parameters to href, etc...

        // Anchor href
        var itemHref = $item.find( 'a:first' ).attr( 'href' );
        // Redirecting the page
        location.href = itemHref;
    }
});
```

Regards

**Comment by WriterStat** [comment]
Way cool.  Will give it a roll.  Much thanks for the code example.

Event-driven it is.  Much safer

Thanks again!  And for the fast response.  Appreciate the fast response.
