### ISSUE TITLE
Make the menu 100% height?  Height of window?  Not of viewport?

### ISSUE THREAD

**Issue by WriterStat** [adgsm/multi-level-push-menu#103]
I'm going to dig into the code.  Thought I'd ask first. But is there a quick way to make the menu height 100% of the window and not the view port? =)

Right now if you open the menu in a non-maximized window, the menu is only the height of the visual view port.  Meaning if you maximize the window, then the menu is only the height of the last visual view port and not actually the height of the maximized window.

Meaning it looks cut off.  Only partially fills the left hand side, vertically.

Thanks for any quick pointer.  I guess I could place a background behind it, that spans 100% of the window height, but that seems a little clunky. I'd like the menu or at least background of it to span to the bottom of the page.  In both maximized and non-maximized views.

I've tried setting the height option to 100%, but doesn't seem to do the trick.

Thanks much for help,

**Comment by adgsm** [comment]
Options
'''
menuHeight: '100%';
'''

**Comment by WriterStat** [comment]
Thanks for the quick response.  Yep. Mentioned above.  But when I do that, and maximize the browser window, it doesn't help.  Still gives me a menu that stops where the content/text in the window stops.  Would liek the menu to go to the bottom of the page.
ex.

_________________
|     |                            |
|     |                            |
|__ |                            |
|                                  |
|                                  |
|_________________|

Menu ends like so above, in maximized browser.  Half way, 100% of the original view port, but not of the maximized page. Wouldn't have bothered you for the option above. =)))   Happens in FF.  Maybe a CSS thing?  But will try the height again, just to make sure.

**Comment by WriterStat** [comment]
whoops...it ate my drawing.

But using the height option only makes it 100% of the original view port size and not 100% of the page/maximized browser window size.  Again though will try it again.

Could be a hiccup.

Cheers,

**Comment by adgsm** [comment]
Use redraw method on browser resize. There is an exsmple doing that in documentation....

**Comment by WriterStat** [comment]
![menu_cut_off](https://cloud.githubusercontent.com/assets/12280348/7556077/200f828e-f728-11e4-8ebc-649fff2e1ea5.gif)

Check out the gif above.  Menu doesn't go to bottom of maximized page.  Hope this helps.  Setting the option doesn't effect this in any of the browsers.

**Comment by WriterStat** [comment]
Gotcha.  Ok.  Thanks!  So the 100% height thing doesn't work for this...I'll need to resize the menu on maximize.  Just was wondering why the Menu is tied to the original view port size and not the page size.

Sorry about the image above, I think we were sending at the same time. =)  best,

Ok, good to know.  Thanks!  And for the cool menu.

**Comment by WriterStat** [comment]
Hi, thanks for all the help.  Ok, tried the Menu redraw method as suggested.  

However doesn't work.  On my laptop if I open the menu in a maximized window using the 100% and the redraw etc... when resized.  It still cuts the menu off just like in the picture above when you scroll down the browser to the bottom of a page. 

$( window ).resize(function() {
    $( '#menu' ).multilevelpushmenu( 'redraw' );
});

Just wanted to alert you.  Seems the menu only goes down as far as the content in it plus any alterations.  Shouldn't the above redraw the menu and get the 100% size right, right?
