### ISSUE TITLE
Getting the object data out of menu.

### ISSUE THREAD

**Issue by WriterStat** [adgsm/multi-level-push-menu#104]
Hi!  Quick question.  Let's say I use the cool add-item to add an item to the Menu.  Is there an easy way to get the Menu object data back out of the menu?

Example:  The menu allows you to pass in a nice JS Object.  It says it's an array, but it's actually an object.  It would be super cool to get that object back out of the menu if the menu is changed or updated.

Is there possibly a quick way to do this?  Thx!  It could be highly useful to your Menu.

I figured since you know the code inside and out, better than I you might give a pointer or a hint.  Before I hack it apart.

I did have thoughts of keeping an object mirror in code, keeping track of where and how the changes were made and changing that instead.  But wanted to check first.

Thanks!  Cheers,

**Comment by adgsm** [comment]
I guess it would be quite straightforward to add something like following
```
if( item.data != undefined ) $item.data( 'data' , item.data );
```
into createItem() method in jquery.multilevelpushmenu.js, so that it looks like as below.
```
// Create item DOM element
function createItem() {
	var item = arguments[0],
		$levelHolder = arguments[1],
		position = arguments[2],
		$itemGroup = $levelHolder.find( 'ul:first' ),
		$item = $( "<li />" );
		( position < ( $itemGroup.find( 'li' ).length ) && position >= 0 ) ? 
			$item.insertBefore( $itemGroup.find( 'li' ).eq( position ) ) : $item.appendTo( $itemGroup );
		$item.attr( { "style" : "text-align: " + ( ( instance.settings.direction == 'rtl' ) ? "right" : "left" ) } );
		if( item.id != undefined ) $item.attr( { "id" : item.id } );
		if( item.data != undefined ) $item.data( 'data' , item.data );
		var $itemAnchor = $( "<a />" )
		.prop( { "href" : item.link } )
		.text( item.name )
		.appendTo( $item ),
		$itemIcon = $( "<i />" )
		.prop( { "class" : ( ( instance.settings.direction == 'rtl' ) ? "floatLeft " : "floatRight " ) + item.icon } )
		.prependTo( $itemAnchor );
	if(item.items) {
		$itemAnchor.bind( clickEventType , function(e){
			itemGroupAnchorClick( e, $levelHolder, $item );
		});
		createItemGroupIcon( $itemAnchor );
		item.items.level = parseInt( $levelHolder.attr( 'data-level' ), 10 ) + 1;
		createNestedDOMStructure(item.items, $item);
	} else {
		$itemAnchor.bind( clickEventType , function(e){
			itemAnchorClick( e, $levelHolder, $item );
		});
	}
}
```
Thereafter you will have data associated with each created item.

**Comment by WriterStat** [comment]
True.  Quite an interesting idea. I'll give it some thought.  Then I could grab them all later, based on the data, using a jQuery find or a map or something.  I'd like to allow users to make real time changes. Then store the entire changed menu structure for them to use again later.  For the next time they open the menu.

Example:  I drop in some code for them to drag and drop menu items to change the order or sort.  I'd like to give them the menu as they left it.  For them, for next time.

The easiest way would be to get the entire menu data back out as a whole, but I guess I could store/apply deltas. 

I've built some of this already.  I already log the changes/deltas as they happen.

Thanks!   I'm kind of pushing the boundaries of this. =)  I realize that, so appreciate the responses.

**Comment by WriterStat** [comment]
Maybe I'm not quite getting this. I admit it's probably my fault. But what I'd like is after a dynamic change or update to the menu is applied, is a way to save that change, basically to access the entire current contents of the updated array for the menu.  To be able to save it.

The above just seems like one item.

I want to save it locally.  Or to a database after that.  Then I'd like to parse that and read it back in,  From the local.  So I need the new current menu array to stringify it before saving it to local.

So if you can point me to a way to get a copy of the current menu array so I can stringify it and save it locally, I'd be much obliged.  Thanks!

Or point me to something better?
