### ISSUE TITLE
completely hide menu

### ISSUE THREAD

**Issue by Yustie** [adgsm/multi-level-push-menu#105]
Hi,

Nice plugin! I was wondering if it's possible to completely hide the menu and show it on a swipe action, like the outlook app microsoft has?

Thanks in advance!

**Comment by adgsm** [comment]
Full collapse example follows.
http://multi-level-push-menu.make.rs/demo/fullexpandcollapse/fullexpandcollapse.html

I'm using Linux so not really aware about what outlook app does...

**Comment by Yustie** [comment]
Where is that blue menu needed for? Does it serve as an example?

**Comment by adgsm** [comment]
yep, it's an example
