### ISSUE TITLE
Object doesn't support property or method 'multilevelpushmenu'

### ISSUE THREAD

**Issue by Yustie** [adgsm/multi-level-push-menu#106]
I keep getting this error message:

> Unhandled exception at line 223, column 9 in http://localhost:2604/
> 0x800a01b6 - JavaScript runtime error: Object doesn't support property or method 'multilevelpushmenu'

The script is loaded, I'm using v2.1.4. Was able to fix the css styling because the css file isn't called "multilevelpushmenu.css", but it's "jquery.pageslide.css".

Can't find "multilevelpushmenu" in the javascript file either.

I'm trying to use this in an asp.net-mvc application, in combination with jquery v2.1.4.

**Comment by adgsm** [comment]
Can you post some code? fiddle even better...

**Comment by Yustie** [comment]
I just copied everything from the menu 'usage'.

include css, include js, html markup. And used this option for show/hide menu:

$(document).ready(function(){
    // HTML markup implementation, overlap mode
    $( '#menu' ).multilevelpushmenu({
        containersToPush: [$( '#pushobj' )],
        fullCollapse: true
    });
});

**Comment by adgsm** [comment]
did you make sure you have jquery.multilevelpushmenu.min.js downloaded and specified correct path to it?

**Comment by Yustie** [comment]
See here a picture that shows that all needed files are loaded:

http://i59.tinypic.com/2mbsx.png

These scripts/css is what I have included:

` <link rel="stylesheet" href="//netdna.bootstrapcdn.com/font-awesome/4.0.1/css/font-awesome.min.css">
    <link href='http://fonts.googleapis.com/css?family=Open+Sans+Condensed:300,300italic,700&subset=latin,cyrillic-ext,latin-ext,cyrillic' rel='stylesheet' type='text/css'>
    <link rel="stylesheet" href="@Url.Content("~/Content/multilevelpushmenu.css")"/>
    <script src="@Url.Content("~/Scripts/jquery.multilevelpushmenu.js")"></script>`

The multilevelpushmenu:

`$(document).ready(function () {
        $('#menu').multilevelpushmenu();
    });`

The html markup is from the usage menu on your website. Too much code to paste here.

Cleared the cache, restarted visual studio, cleaned the solution. I've tried everything I could think of.

**Comment by Yustie** [comment]
Think I found the problem, you're using an older version of jquery:
`<script src="//ajax.googleapis.com/ajax/libs/jquery/1.10.2/jquery.min.js"></script>`
And I'm using v2.1.4.

When removing v2 and using v1.10.2, it seems to work. I have tried  v2.1.4. in combination with the migrate version of jquery, but that doesn't work, same crash.

Using v2.1.4 and v1.10.2, doesn't work either. I can't lose v2.1.4. So is there any chance you could make it compatible with jquery version 2 and up?

**Comment by adgsm** [comment]
No, at least not in next couple of months...

**Comment by Yustie** [comment]
Will it take that long? What needs to be altered for this to work? I'll try it myself in the mean time and see how far I'll get.

**Comment by adgsm** [comment]
i'm not really sure... would have to look closely at it; i have developed it more than a year ago... since i'm currently engaged in the other project i will not have time in next 2-3 months to take a closer look on it, sorry...

**Comment by Yustie** [comment]
It seems to working now with the latest version of jQuery. Closing this issue.
