### ISSUE TITLE
How to scroll in the menu?

### ISSUE THREAD

**Issue by Yustie** [adgsm/multi-level-push-menu#107]
Is it possible to scroll in the menu when there are too many links?

**Comment by adgsm** [comment]
It should be fairly easy to use some scrolling plugin/tool (e.g. iscroll) with it.
Following is jsfiddle using iscroll for scrolling menu

https://jsfiddle.net/vpp2ub0h/

**Comment by Yustie** [comment]
I don't know what exactly is going wrong, but the height and width are crazy. I'm setting this up in an ASP.NET-MVC application, and this is what the rendered HTML looks like (look at the `width: 28869` and `min-height:1870px` of the `div` tag having id=menu):

`<div id="menu" style="width: 28869px; height: 1870px; min-height: 1870px; min-width: 28869px;">
<nav class="mlpm_w" id="menu_multilevelpushmenu" style="height: 100%; min-height: 1870px; min-width: 28869px;"><div class="levelHolderClass ltr" style="width: 28869px; margin-left: 0px; transform: translate(0px, 0px) translateZ(0px); transition-duration: 0ms; transition-timing-function: cubic-bezier(0.1, 0.57, 0.1, 1);" data-level="0"><h2 style="text-align: left;"><i class="floatRight cursorPointer fa fa-reorder"></i>All Categories</h2><ul><li style="text-align: left;"><a href="#"><i class=" floatLeft iconSpacing_ltr fa fa-angle-left"></i><i class="floatRight fa fa-laptop"></i>Devices</a><div class="levelHolderClass ltr" style="width: 28869px; margin-left: -57738px;" data-level="1"><h2 style="text-align: left;"><i class="floatRight cursorPointer fa fa-laptop"></i>Devices</h2><div class="backItemClass"><a href="#"><i class="floatRight fa fa-angle-right"></i>Back</a></div><ul><li style="text-align: left;"><a href="#"><i class=" floatLeft iconSpacing_ltr fa fa-angle-left"></i><i class="floatRight fa fa-phone"></i>Mobile Phones</a><div class="levelHolderClass ltr" style="width: 28869px; margin-left: -57738px;" data-level="2"><h2 style="text-align: left;"><i class="floatRight cursorPointer fa fa-phone"></i>Mobile Phones</h2><div class="backItemClass"><a href="#"><i class="floatRight fa fa-angle-right"></i>Back</a></div><ul><li style="text-align: left;"><a href="#"><i class="floatRight undefined"></i>Super Smart Phone</a></li><li style="text-align: left;"><a href="#"><i class="floatRight undefined"></i>Thin Magic Mobile</a></li><li style="text-align: left;"><a href="#"><i class="floatRight undefined"></i>Performance Crusher</a></li><li style="text-align: left;"><a href="#"><i class="floatRight undefined"></i>Futuristic Experience</a></li><li style="text-align: left;"><a href="#"><i class="floatRight undefined"></i>Super Smart Phone</a></li><li style="text-align: left;"><a href="#"><i class="floatRight undefined"></i>Thin Magic Mobile</a></li><li style="text-align: left;"><a href="#"><i class="floatRight undefined"></i>Performance Crusher</a></li><li style="text-align: left;"><a href="#"><i class="floatRight undefined"></i>Futuristic Experience</a></li><li style="text-align: left;"><a href="#"><i class="floatRight undefined"></i>Super Smart Phone</a></li><li style="text-align: left;"><a href="#"><i class="floatRight undefined"></i>Thin Magic Mobile</a></li><li style="text-align: left;"><a href="#"><i class="floatRight undefined"></i>Performance Crusher</a></li><li style="text-align: left;"><a href="#"><i class="floatRight undefined"></i>Futuristic Experience</a></li><li style="text-align: left;"><a href="#"><i class="floatRight undefined"></i>Super Smart Phone</a></li><li style="text-align: left;"><a href="#"><i class="floatRight undefined"></i>Thin Magic Mobile</a></li><li style="text-align: left;"><a href="#"><i class="floatRight undefined"></i>Performance Crusher</a></li><li style="text-align: left;"><a href="#"><i class="floatRight undefined"></i>Futuristic Experience</a></li></ul></div></li><li style="text-align: left;"><a href="#"><i class=" floatLeft iconSpacing_ltr fa fa-angle-left"></i><i class="floatRight fa fa-desktop"></i>Televisions</a><div class="levelHolderClass ltr" style="width: 28869px; margin-left: -57738px;" data-level="2"><h2 style="text-align: left;"><i class="floatRight cursorPointer fa fa-desktop"></i>Televisions</h2><div class="backItemClass"><a href="#"><i class="floatRight fa fa-angle-right"></i>Back</a></div><ul><li style="text-align: left;"><a href="#"><i class="floatRight undefined"></i>Flat Super Screen</a></li><li style="text-align: left;"><a href="#"><i class="floatRight undefined"></i>Gigantic LED</a></li><li style="text-align: left;"><a href="#"><i class="floatRight undefined"></i>Power Eater</a></li><li style="text-align: left;"><a href="#"><i class="floatRight undefined"></i>3D Experience</a></li><li style="text-align: left;"><a href="#"><i class="floatRight undefined"></i>Classic Comfort</a></li></ul></div></li><li style="text-align: left;"><a href="#"><i class=" floatLeft iconSpacing_ltr fa fa-angle-left"></i><i class="floatRight fa fa-camera-retro"></i>Cameras</a><div class="levelHolderClass ltr" style="width: 28869px; margin-left: -57738px;" data-level="2"><h2 style="text-align: left;"><i class="floatRight cursorPointer fa fa-camera-retro"></i>Cameras</h2><div class="backItemClass"><a href="#"><i class="floatRight fa fa-angle-right"></i>Back</a></div><ul><li style="text-align: left;"><a href="#"><i class="floatRight undefined"></i>Smart Shot</a></li><li style="text-align: left;"><a href="#"><i class="floatRight undefined"></i>Power Shooter</a></li><li style="text-align: left;"><a href="#"><i class="floatRight undefined"></i>Easy Photo Maker</a></li><li style="text-align: left;"><a href="#"><i class="floatRight undefined"></i>Super Pixel</a></li></ul></div></li></ul></div></li><li style="text-align: left;"><a href="#"><i class=" floatLeft iconSpacing_ltr fa fa-angle-left"></i><i class="floatRight fa fa-book"></i>Magazines</a><div class="levelHolderClass ltr" style="width: 28869px; margin-left: -57738px;" data-level="1"><h2 style="text-align: left;"><i class="floatRight cursorPointer fa fa-book"></i>Magazines</h2><div class="backItemClass"><a href="#"><i class="floatRight fa fa-angle-right"></i>Back</a></div><ul><li style="text-align: left;"><a href="#"><i class="floatRight undefined"></i>National Geographics</a></li><li style="text-align: left;"><a href="#"><i class="floatRight undefined"></i>Scientific American</a></li><li style="text-align: left;"><a href="#"><i class="floatRight undefined"></i>The Spectator</a></li><li style="text-align: left;"><a href="#"><i class="floatRight undefined"></i>Rambler</a></li><li style="text-align: left;"><a href="#"><i class="floatRight undefined"></i>Physics World</a></li><li style="text-align: left;"><a href="#"><i class="floatRight undefined"></i>The New Scientist</a></li></ul></div></li><li style="text-align: left;"><a href="#"><i class=" floatLeft iconSpacing_ltr fa fa-angle-left"></i><i class="floatRight fa fa-shopping-cart"></i>Store</a><div class="levelHolderClass ltr" style="width: 28869px; margin-left: -57738px;" data-level="1"><h2 style="text-align: left;"><i class="floatRight cursorPointer fa fa-shopping-cart"></i>Store</h2><div class="backItemClass"><a href="#"><i class="floatRight fa fa-angle-right"></i>Back</a></div><ul><li style="text-align: left;"><a href="#"><i class=" floatLeft iconSpacing_ltr fa fa-angle-left"></i><i class="floatRight fa fa-tags"></i>Clothes</a><div class="levelHolderClass ltr" style="width: 28869px; margin-left: -57738px;" data-level="2"><h2 style="text-align: left;"><i class="floatRight cursorPointer fa fa-tags"></i>Clothes</h2><div class="backItemClass"><a href="#"><i class="floatRight fa fa-angle-right"></i>Back</a></div><ul><li style="text-align: left;"><a href="#"><i class=" floatLeft iconSpacing_ltr fa fa-angle-left"></i><i class="floatRight fa fa-female"></i>Women's Clothing</a><div class="levelHolderClass ltr" style="width: 28869px; margin-left: -57738px;" data-level="3"><h2 style="text-align: left;"><i class="floatRight cursorPointer fa fa-female"></i>Women's Clothing</h2><div class="backItemClass"><a href="#"><i class="floatRight fa fa-angle-right"></i>Back</a></div><ul><li style="text-align: left;"><a href="#"><i class="floatRight undefined"></i>Tops</a></li><li style="text-align: left;"><a href="#"><i class="floatRight undefined"></i>Dresses</a></li><li style="text-align: left;"><a href="#"><i class="floatRight undefined"></i>Trousers</a></li><li style="text-align: left;"><a href="#"><i class="floatRight undefined"></i>Shoes</a></li><li style="text-align: left;"><a href="#"><i class="floatRight undefined"></i>Sale</a></li></ul></div></li><li style="text-align: left;"><a href="#"><i class=" floatLeft iconSpacing_ltr fa fa-angle-left"></i><i class="floatRight fa fa-male"></i>Men's Clothing</a><div class="levelHolderClass ltr" style="width: 28869px; margin-left: -57738px;" data-level="3"><h2 style="text-align: left;"><i class="floatRight cursorPointer fa fa-male"></i>Men's Clothing</h2><div class="backItemClass"><a href="#"><i class="floatRight fa fa-angle-right"></i>Back</a></div><ul><li style="text-align: left;"><a href="#"><i class="floatRight undefined"></i>Shirts</a></li><li style="text-align: left;"><a href="#"><i class="floatRight undefined"></i>Trousers</a></li><li style="text-align: left;"><a href="#"><i class="floatRight undefined"></i>Shoes</a></li><li style="text-align: left;"><a href="#"><i class="floatRight undefined"></i>Sale</a></li></ul></div></li></ul></div></li><li style="text-align: left;"><a href="#"><i class="floatRight undefined"></i>Jewelry</a></li><li style="text-align: left;"><a href="#"><i class="floatRight undefined"></i>Music</a></li><li style="text-align: left;"><a href="#"><i class="floatRight undefined"></i>Grocery</a></li></ul></div></li><li style="text-align: left;"><a href="#"><i class="floatRight undefined"></i>Collections</a></li><li style="text-align: left;"><a href="#"><i class="floatRight undefined"></i>Credits</a></li></ul></div></nav></div>`

These are all the css and scripts I've included:

<link rel="stylesheet" href="@Url.Content("~/Content/site.css")" />
<link rel="stylesheet" href="@Url.Content("~/Content/font-awesome.min.css")" />
<link rel="stylesheet" href="@Url.Content("~/Content/multilevelpushmenu.css")"/>

<script src="@Url.Content("~/Scripts/jquery-2.1.4.min.js")"></script>
<script src="@Url.Content("~/Scripts/modernizr-2.8.3.js")"></script>
    
<script src="@Url.Content("~/Scripts/IScroll/core.js")"></script>
<script src="@Url.Content("~/Scripts/IScroll/utils.js")"></script>
<script src="@Url.Content("~/Scripts/jquery.multilevelpushmenu.js")"></script>

Any idea what I might be doing wrong?
