### ISSUE TITLE
Destroy and re-init menu? how?

### ISSUE THREAD

**Issue by WriterStat** [adgsm/multi-level-push-menu#124]
I use:
$('#menu').empty();

Which removes the menu from the existing page.

Then I re-init the menu.  Using the existing $('menu').multilevelpushmenu({...});

Which surprisingly works.

Except when it comes back it is in cover mode, no matter what you do. 

When you click on something it then returns to overlap mode, but from that point on it is 40 pixels off.

I've tried deleting the instance and re-init, but doesn't work for me. I've tried resetting the instance settings.  This seems to get ignored, doesn't work for me.

Not asking for a code change, just a pointer to why it comes back in cover mode rather than the pre-set  settings of overlap?  Puling my hair out. =)

Thanks for any info you can provide.

**Comment by Psyphant** [comment]
You can destroy the menu with the following two calls:
$("#menu").find("nav#div_multilevelpushmenu").remove(); // to remove the html wrapper
and
$("#menu")..removeData('plugin_multilevelpushmenu'); // this clears old configuration data

**Comment by WriterStat** [comment]
Hi Christopher, Thanks!

We ended up going in another direction. While the author is great and the demo is great!

It just had challenges in real world applications.

Thanks!

And definitely thanks to the author and the demo!
