### ISSUE TITLE
group title (?) click event ?

### ISSUE THREAD

**Issue by yvesbe** [adgsm/multi-level-push-menu#128]
Hi there, 
i might have a little problem (yes, myself is one, but another)  : I found the "onTitleItemClick" event which triggers when you click the icon which is next the group title (you know, the H2 element).. 
But it would be nice if there was an event which triggers when you click on the group title itself.
Is there one i missed ? Is there a way to trigger such an event ?

**Comment by adgsm** [comment]
http://multi-level-push-menu.make.rs/#events
onGroupItemClick:                  // Click/touchstart menu item containing sub-items

**Comment by yvesbe** [comment]
I apologize, but it's not what i mean. (sorry i'm not english speaker). 
the onGroupItemClick is triggered when you want to open a submenu, before seeing its content and submenu. . 

I want to trigger an event when i already entered that submenu, when click on the title of that submenu i am already in. 

You can see what i mean here : 
http://www.lachatterie.be/ . 
You can see the rolling star icon, and on it's left the text "Le Coeur d'Orion". 
onGroupitemClick will trigger if i click the star, but not if i click on "Le Coeur d'Orion".
I'd like to have a click event linked to "Le Coeur d'Orion" item itself, and the same behaviour in the same kind of items in submenus. 

i hope i'm understandable :s

**Comment by adgsm** [comment]
I guess then you should change line 197 from
```
$titleIcon.bind( clickEventType ,  function(e){
```
to
```
$title.bind( clickEventType ,  function(e){
```

**Comment by yvesbe** [comment]
Allright... this works but slightly differently. 
This might interest you : 
as i'm not working with the same version, i didn't change anything on line 197 but on line 

this means that i didn't work on 
function createNestedDOMStructure() , but on 
function updateNestedDOMStructure( $wrapper ) instead. 

i don't know if my changes must be included in createNestedDOMStructure() , but in my tests, nothing was triggered there. 


modified jquery.multilevelpushmenu.js v2.0.9

added: 
onTitleClick: function() {},    // by Yco line 51

added on line 190
$title.bind( clickEventType , function(e){
	titleClick(e, $levelHolder, $wrapper);
});

added line 220 
			function titleClick( e, $levelHolder, menus ) {
				if( $(instance).find( 'div.levelHolderClass' ).is(':animated') ) return false;
				instance.settings.onTitleClick.apply(this, Array.prototype.slice.call([e, $levelHolder, instance.settings]));
				stopEventPropagation(e);
				var instanceFC = ( instance.settings.direction == 'rtl' ) ?
					parseInt( $levelHolder.css( 'margin-right' ) ) < 0
					:
					parseInt( $levelHolder.css( 'margin-left' ) ) < 0;
				if( menus.level == 0 && instanceFC ) {
					expandMenu();
				}
				else {
					var $nextLevelHolders = instance.settings.container
						.find( '#' + instance.settings.menuID + ' div.levelHolderClass' )
						.filter(function(){
							var retObjs = ( instance.settings.direction == 'rtl' ) ?
							(($( this ).attr( 'data-level' ) > $levelHolder.attr( 'data-level' )) && ( parseInt( $( this ).css( 'margin-right' ) ) >= 0 ) )
							:
							(($( this ).attr( 'data-level' ) > $levelHolder.attr( 'data-level' )) && ( parseInt( $( this ).css( 'margin-left' ) ) >= 0 ) );
							return retObjs;
						}),
						$prevLevelHolders = instance.settings.container
						.find( '#' + instance.settings.menuID + ' div.levelHolderClass' )
						.filter(function(){
							var retObjs = ( instance.settings.direction == 'rtl' ) ?
							(($( this ).attr( 'data-level' ) <= $levelHolder.attr( 'data-level' )) && ( parseInt( $( this ).css( 'margin-right' ) ) >= 0 ) )
							:
							(($( this ).attr( 'data-level' ) <= $levelHolder.attr( 'data-level' )) && ( parseInt( $( this ).css( 'margin-left' ) ) >= 0 ) );
							return retObjs;
						}),
						collapseAll = ( $nextLevelHolders.length == 0 && $prevLevelHolders.length == 1 ) ? collapseMenu() : collapseMenu( parseInt( $levelHolder.attr( 'data-level' ) ) );
				}
				$levelHolder.css( 'visibility' , 'visible' );
				$levelHolder.find( '.' + instance.settings.backItemClass ).css( 'visibility' , 'visible' );
				$levelHolder.find( 'ul' ).css( 'visibility' , 'visible' );
				$levelHolder.removeClass( instance.settings.menuInactiveClass );
			}


The result is that it seams therer is a new event available: 
onTitleClick: function() {}
