### ISSUE TITLE
Loaded all files and my home page has only the markup, not Styled to appear as a Menu

### ISSUE THREAD

**Issue by landmarkads** [adgsm/multi-level-push-menu#133]
My home page only shows the <ul> and lists in the markup format, there is no dynamic menu or styling. I loaded the .js files and .css files in my root directory.

**Comment by adgsm** [comment]
Looks like not all files are loaded... please check is demo working for you...

**Comment by landmarkads** [comment]
Thank you for your response. I figured it out and you are right. The push menu won't run with jquery version 1.11.3, I needed to use jquery 2.1.4. Also, some other code that made it work:

<a class="menu-trigger" href="#menu"><i class="ss-icon">&#xED50;</i>
</a>
	<nav id="menu" style="display: none;">

The style attribute is necessary or the menu appears twice and the "ss-icon" and corresponding unicode is good if you want the little symbol.
