### ISSUE TITLE
Problems with Bootstrap and mobile devices

### ISSUE THREAD

**Issue by radscheit** [adgsm/multi-level-push-menu#134]
Hello, MLPM works fine as long as the screen width ist at md-size or bigger. But when I resize to a typical tablet resolution, it disappears: http://p262957.mittwaldserver.info/drupal/

I tried it with increasing the z-index but it didn't worked.

Any suggestions would be helpful.

Thanks in advance!

**Comment by adgsm** [comment]
Hello, It looks to me that it doesn't disappear but is being pushed by

```
<div class="col-lg-12" id="content-container" style="
    display: table-cell;
">
```
bellow visible area...
If you, for example set it to display: none in chrome developer tools you will see menu appearing again...

**Comment by radscheit** [comment]
OK, thanks for the quick answer!
