### ISSUE TITLE
thi

### ISSUE THREAD

**Issue by JSON12345** [adgsm/multi-level-push-menu#137]
hi sir,
i am trying to implement third level menu in website but category.tpl is not working properly
plz help me in that
my email is jsonforit@gmail.com

the code is :+1: 

<div class="list-category list-group">
  <?php foreach ($categories as $category) { ?>
  <?php if ($category['category_id'] == $category_id) { ?>
  <a href="<?php echo $category['href']; ?>" class="list-group-item active"><i class="fa fa-asterisk"></i><?php echo $category['name']; ?></a>
  <?php if ($category['children']) { ?>
  <div class="chil-list">
  <?php foreach ($category['children'] as $child) { ?>
  <?php if ($child['category_id'] == $child_id) { ?>
  <a href="<?php echo $child['href']; ?>" class="list-group-item active">&nbsp;&nbsp;&nbsp;- <?php echo $child['name']; ?></a>
 
 <?php if(isset($child['children_lv3']) && count($child['children_lv3'])>0){ ?>
                		<ul> 
                               <?php foreach ($child['children_lv3'] as $child_lv3) { ?>
                               <li><a href="<?php echo $child_lv3['href']; ?>"><?php echo $child_lv3['name']; ?></a></li>
                                <?php  } ?>
                            </ul>
                        <?php } ?>

<?php } else { ?>
  <a href="<?php echo $child['href']; ?>" class="list-group-item">&nbsp;&nbsp;&nbsp;- <?php echo $child['name']; ?></a>
  <?php } ?>
  <?php } ?>
  </div>
  <?php } ?>
  <?php } else { ?>
  <a href="<?php echo $category['href']; ?>" class="list-group-item"><i class="fa fa-asterisk"></i><?php echo $category['name']; ?></a>
  <?php } ?>
  <?php } ?>
</div>

**Comment by adgsm** [comment]
Do you have an example of what is not working? What is category.tpl?

**Comment by JSON12345** [comment]
category.tpl file of opencart extension which is responsible for generating third level menu 


code is already given in post if you unable to see pls send me ur email id
thanku

**Comment by adgsm** [comment]
Sorry I'm not knowledgable about OpenCart so can not offer you any support in that regards... Maybe you should try OpenCart support options...
Regards

**Comment by JSON12345** [comment]
its ok
