### ISSUE TITLE
Wait for an event of a sub menu and not from the all menu

### ISSUE THREAD

**Issue by rrfranco92** [adgsm/multi-level-push-menu#138]
Hey,

Is it possible to wait for an event, such as onExpandMenuStart but for a sublevel and not for the main menu?

**Comment by adgsm** [comment]
It should be fired for any level stared to expanding...

**Comment by rrfranco92** [comment]
Sorry, didn't get it.

Can I call this event only when the menu is in data-level 3 for example?

**Comment by adgsm** [comment]
Event will be fired always on expanding but there is an method to determine active level. Please look at list of methods here - http://multi-level-push-menu.make.rs/#methods.
```
/**
 * Active (last expanded) menu level
 * Returns active menu level object, or false if menu is fully collapsed
 */
$('#menu').multilevelpushmenu('activemenu');
```
So you can use it in your event callback method to whatever you need to do at level 3...

**Comment by rrfranco92** [comment]
even when trying to increase the overlapWidth and the menu width? I was trying to get different width values from step to step..

**Comment by adgsm** [comment]
Obtaining active menu level is irrelevant to overlapWidth, but setting different width for each sub-menu I've never tried and from blind guess I would say it will not work...
