### ISSUE TITLE
Initializing Menu From AngularJS Directive

### ISSUE THREAD

**Issue by MarcGervais** [adgsm/multi-level-push-menu#139]
I am using AngularJS in my project and I am trying to get the menu initialized from within a custom directive as my menu data is coming from a web service call.

I have the menu being initialized, but the Font Awesome icons that are usually right-aligned are now left-aligned and I cannot see the issue. Is there anything you can think of that may cause this behavior?

Thanks.

**Comment by adgsm** [comment]
(Have no idea) can you share an example online?

**Comment by adgsm** [comment]
Sorry I have no sufficient knowledge about angular... maybe someone else can help better...
