### ISSUE TITLE
Adding Forms to Menu Items

### ISSUE THREAD

**Issue by Coop56** [adgsm/multi-level-push-menu#141]
Is it possible to add forms with items?

So for example you'd have an item called Chapter Title and you'd include a small form below that for a user to input and save data prior to the next item in the list.  I'm using the BasicJS method right now to populate my menu.

I'm just curious if someone has already done this with this plugin before I start adding this functionality from scratch.

Thanks.

**Comment by adgsm** [comment]
Take a look at this jsfiddle http://jsfiddle.net/5rjg9/

There is also a conversation in same regards here #10

**Comment by Coop56** [comment]
Ok taking a look - how would I add this to the BasicJS implementation?  What section would the custom HTML go in?

**Comment by adgsm** [comment]
You can put form as item text and thereafter change following line in jquery.multilevelpushmenu.js
https://github.com/adgsm/multi-level-push-menu/blob/master/jquery.multilevelpushmenu.js#L351
put
```
.html( item.name )
```
instead of
```
.text( item.name )
```

You can see an example here http://jsfiddle.net/5rjg9/223/

**Comment by Coop56** [comment]
Thanks - I got some of it working as intended.  Should angular work inside of name now that we've changed it to .html?

I'm using some Angular to call a function, it was working in the HTML way but when I moved it into a JS Array to generate the menu it stopped working.

For example:

name: '<a id="addchapter" ng-click="addChapter();">Add a new chapter</a>'

**Comment by adgsm** [comment]
Sorry, I have no idea about how to make in work with angular...
