### ISSUE TITLE
jquery-2.2.2 does'nt work

### ISSUE THREAD

**Issue by oitsuki** [adgsm/multi-level-push-menu#145]
hello,

The script doesn' work with jquery-2.2.2.min.js

  <script src="https://code.jquery.com/jquery-2.2.2.min.js" integrity="sha256-36cp2Co+/62rEAAYHLmRCPIych47CvdM+uTBJwSzWjI=" crossorigin="anonymous"></script>

**Comment by adgsm** [comment]
Hi,

Correct, the main focus of the plugin was to make use of Codrops MultiLevelPushMenu functional in older browsers (i.e. IE 8). For any other purpose I encourage you to use better / original Codrops MultiLevelPushMenu, as stated in documentation.

Regrads
