### ISSUE TITLE
'additems' into root menu level 0

### ISSUE THREAD

**Issue by goldweb** [adgsm/multi-level-push-menu#148]
Is it possible to add some new [items|menus] to the top root level of our menu by using 'additems'? Or some other js method.

**Comment by adgsm** [comment]
You can instantiate as much menus as you like in the same page. Add menu items is possible at any level.

**Comment by goldweb** [comment]
Can you bring here example of code, how to add menu or item at the most top level of our main menu?

**Comment by adgsm** [comment]
Same as http://multi-level-push-menu.make.rs/#exampleaddremove, just specify in $addTo div menu instance of a menu you would like to populate...

**Comment by adgsm** [comment]
in case of example you can find root level with
```
$( 'div[data-level="0"]' )
```

**Comment by goldweb** [comment]
Ok, thanks I will try it. So I think You can close it.

**Comment by goldweb** [comment]
Big Thanks
