### ISSUE TITLE
How to Cancel Swipe Desktop and Mobile?

### ISSUE THREAD

**Issue by mehmetalidumlu** [adgsm/multi-level-push-menu#153]
Hi all,
I put a slider in multi level push menu. But when i change slider value with using mouse o touch on screen then menu collepse. Can you help me about this?

**Comment by adgsm** [comment]
Try

```
return false;
```

for appropriate event callback similar as explained in issue #63

**Comment by mehmetalidumlu** [comment]
It works :) Thank you so much
