### ISSUE TITLE
links are not working inside submenu

### ISSUE THREAD

**Issue by sathishtb** [adgsm/multi-level-push-menu#155]
We have multiple  anchor tag's(EXPLORE,BUILD) inside the submenu after expanding root level,like attached screenshot. But when clicking an anchor tag,the hyperlink(href)  is not invoked,even normal jquery events are not get called. Can you please help me to fix this?

![image](https://cloud.githubusercontent.com/assets/22075764/18348773/fb877258-75ea-11e6-94ef-1f37f499ecc4.png)

**Comment by plarmuseau** [comment]
hello

i don't understand how to make the links working ?
http://gaverapotheek.be/wiz/intro2.php

**Comment by adgsm** [comment]
It is explained [here](http://multi-level-push-menu.make.rs/#options) and [here](http://multi-level-push-menu.make.rs/#events)
