### ISSUE TITLE
Full Path

### ISSUE THREAD

**Issue by AbhinavWase** [adgsm/multi-level-push-menu#163]
Hi, 
Please help me in getting full path (path from root to item clicked) of clicked menu node.

**Comment by adgsm** [comment]
Please check documentation.
``
/**
 * Find path to root of selected menu level object
 * Provides chain collection of menu level objects (root menu level object to given menu level object), or false in case of error
 */
$('#menu').multilevelpushmenu('pathtoroot', $menuLevelObject);

```

**Comment by AbhinavWase** [comment]
I've gone through documentation, but no luck. Please let me brief my requirement 
I'm using MultiLevelPushMenu, onwhich I'm using bootstrap context menu where I need to have option for creating folders, pages and edit options like copy edit and paste. 

any example of return path will be highly appreciated.

Thanks,

**Comment by adgsm** [comment]
Please check my previous answer. I have pasted in there from documentation an method which will provide you path from curently expanded menu to the root. Here it is once again below.

```
$('#menu').multilevelpushmenu('pathtoroot', $menuLevelObject);
```

**Comment by AbhinavWase** [comment]
sorry to ask this again, I'm getting object as alert but not able to dig down into same, attached the screenshot of what I'm getting.
I'm new to Jquery, could you please help me in getting path into string format from this object...

Thanks again...

here's my code 

$(document).ready(function(){
	// HTML markup implementation, overlap mode
	$( '#menu' ).multilevelpushmenu({
		containersToPush: [$( '#pushobj' )],
		menuWidth: '25%',
		menuHeight: '100%',
         onItemClick: function() {
        // First argument is original event object
        var event = arguments[0],
            // Second argument is menu level object containing clicked item (<div> element)
            $menuLevelHolder = arguments[1],
            // Third argument is clicked item (<li> element)
            $item = arguments[2],
            // Fourth argument is instance settings/options object
            options = arguments[3];

        // You can do some cool stuff here before
        // redirecting to href location
        // like logging the event or even
        // adding some parameters to href, etc...
        var path = $('#menu').multilevelpushmenu('pathtoroot', $item);
       
        alert(path);
    }
	});
});
![cap](https://cloud.githubusercontent.com/assets/24935795/21744387/5f6389e8-d53a-11e6-8042-500917b686b9.png)

**Comment by AbhinavWase** [comment]
any luck for this?
codepen or jsfiddle?
