### ISSUE TITLE
Path To Root 

### ISSUE THREAD

**Issue by AbhinavWase** [adgsm/multi-level-push-menu#164]
Any luck over issue #163 
Codepen or Fiddle for the same?

Thanks a Ton.

**Comment by adgsm** [comment]
Hey, there is no issue with the code, right? Debugging using javascript alert is definitely not advisable... There are much better ways to do it though...
I have no time to write code for you for your project, please take a closer look yourself on what you want to achieve.
Regards

**Comment by AbhinavWase** [comment]
How would I know that there is no issue in your code till I get result or know what I'm doing wrong that is the reason I asked you right, being owner you should be able to answer the simple question instead or replying many many times.
anyways, sorry to waste your time, I'll find my way out or use some another plugin. 
Thanks and Regards.
