### ISSUE TITLE
Separate events for menu text and icon 

### ISSUE THREAD

**Issue by m-menon** [adgsm/multi-level-push-menu#169]
hi,

Is it possible to separate the events for the menu text and the icon? I have attached a screenshot of what I am trying to describe. 
![seperate_events_for_text_and_icon](https://cloud.githubusercontent.com/assets/10776430/23153286/a2970886-f842-11e6-8e89-2edcc7a72fa2.jpg)

I have a situation where the user clicks the menu text and it displays some popup stuff and when he clicks on the symbol (the icon to the right), I'd want to position the marker on a map. Is there a easy way to this? Thanks for the awesome plugin :)

Cheers,
M.M

**Comment by adgsm** [comment]
Take a look at #9

**Comment by m-menon** [comment]
Cool !!! Cheers ,,,M.M :100:
