### ISSUE TITLE
100% of div width and height

### ISSUE THREAD

**Issue by m-menon** [adgsm/multi-level-push-menu#170]
hi,

Thanks for the great plugin. Any pointers on how I could get the menu to occupy the complete width and height of the sidebar (in which it is placed). Thanks M.M

Oh ya and I am using covermode

![full_div_occupy](https://cloud.githubusercontent.com/assets/10776430/23290208/0fb202ec-fa8a-11e6-99aa-0a9a70823e0c.jpg)

**Comment by adgsm** [comment]
Take a look at available options [here](http://multi-level-push-menu.make.rs/#options). With and height are available options as well. Also check examples provided, maybe to copy/paste from it...

**Comment by m-menon** [comment]
Cool ... thanks a ton :+1:
