### ISSUE TITLE
Sorting

### ISSUE THREAD

**Issue by m-menon** [adgsm/multi-level-push-menu#171]
hi,

Is there a way to sort this? I could perhaps sort the array or the input and then recreate the menu but was wondering if there is a method to achieve this easily? Thanks - M.M

**Comment by adgsm** [comment]
No sorting is built in.

**Comment by m-menon** [comment]
You mean there is no built-in sorting? Or 

> No, sorting is built in

If the later is true, is there a link to it?

Thanks

**Comment by adgsm** [comment]
there is no sorting functionality out-of-the-box...

**Comment by m-menon** [comment]
Alrighty, thanks. I will use the JS Array then - that way I could sort it first then use that to populate the menu. Thanks :+1:
