### ISSUE TITLE
Show menu top upon clicking a menu item that has sub menu items under it

### ISSUE THREAD

**Issue by Sue-k** [adgsm/multi-level-push-menu#178]
Hi,

The main menu is longer than the mobile device screen size so when the bottom menu item is clicked (which has less items/links under it than the main menu) the focus remains at the bottom (which is blank as there aren't enough menu items under it) instead of shifting the focus to the top. I have to scroll to the top to see the items under selected menu. Is there any way to show/focus the top of the menu when a menu item/link (containing sub-menu items) is clicked so the user can see the menu without having to scroll to the top? I hope I described this correctly. Any help would be nice.

**Comment by adgsm** [comment]
Why don't you scroll menu container div to the top using onCollapseMenuEnd and onExpandMenuEnd methods?
Something like following.
```
onExpandMenuEnd: function(){
    var myMenuContainer = document.getElementById('myMenuContainer');
    myMenuContainer.scrollTop = 0;
};
```

**Comment by Sue-k** [comment]
scrollTop worked. Thx!
