### ISSUE TITLE
Expanding to a level object when more than one have the same name

### ISSUE THREAD

**Issue by bingimar** [adgsm/multi-level-push-menu#186]
I'm trying to expand to a specific menu level id.

I have multiple objects with the same name but different id's. How is this achievable?

**Comment by adgsm** [comment]
Yes, it is. Recommended way to expand the menu is invoking the expand method using jquery div object as second parameter (2nd one below), where $menuLevelObject in your case would be ```$('#your_menu_id_here')```

```
/**
 * Expand menu
 */
// Menu expand from fully collapsed mode to level 0
$('#menu').multilevelpushmenu('expand');

// Expand menu up to the $menuLevelObject
$('#menu').multilevelpushmenu('expand', $menuLevelObject);

// Expand menu up to the menu level object with title 'Devices' (not recommended since there could be many menu level objects with the same title; in such cases expanding will be unsuccessful)
$('#menu').multilevelpushmenu('expand', 'Devices');
```

**Comment by bingimar** [comment]
ok, I wasn't sure on what $menuLevelObject was, but its essentially the object which has the title field not the name.

Thanks.
