### ISSUE TITLE
How to toggle menu

### ISSUE THREAD

**Issue by Err0r404** [adgsm/multi-level-push-menu#25]
Hi,

I'm trying to toggle (expand/collapse) menu by pressing only one button but can't get the current status...
Method "menuexpanded" always return me false.

Could you provide a simple example on how to know if menu is expanded or collapsed no matter the level ?

Or just provide a new method that automatically toggle menu ?

Thanks !

EDIT : 
@adgsm Works nicely ! Thanks ! But please consider adding a "toggle" method ;)

**Comment by dirkml** [comment]
Would it be possible to have the same but working with HTML markup menu ? 
Many thanks :)

**Comment by rafaelblink** [comment]
Thank you adgsm.

**Comment by aaronsummers** [comment]
Thanks, I updated the code slightly and used the **active menu** as the second paramiter for the menu expanded function.

``` js
$( '#expand-button' ).click(function(){
	var menu = $('#push-menu');
    var menuExpanded = menu.multilevelpushmenu( 'menuexpanded', menu.multilevelpushmenu( 'activemenu' ) );

    if( menuExpanded ){
        menu.multilevelpushmenu( 'collapse' );
    }
    else {
        menu.multilevelpushmenu( 'expand' );
    }
});
```
