### ISSUE TITLE
Can't check checkbox in menu

### ISSUE THREAD

**Issue by lavrton** [adgsm/multi-level-push-menu#34]
Demo: http://jsfiddle.net/lavrton/MRr4d/1/
It was working with v2.0.9

**Comment by Graahf** [comment]
Having a similar issue, but my checkbox is inside the menu (level 3), not on the top level.

When I check the checkbox, it either unchecks or does not get checked.

I'm using the same code you wrote, but not working :(

**Comment by cferenc** [comment]
I checks my thing with chrome, it works but in Firefox and internet explorer doesn't, so it might be a good idea to check it in the same way. I guess the problem is around browser version.
Frank

Get Outlook for Android<https://aka.ms/ghei36>

________________________________
