### ISSUE TITLE
Bounding a menu in a scrollable div

### ISSUE THREAD

**Issue by graycarper** [adgsm/multi-level-push-menu#49]
Howdy! This question will probably boil down to CSS and not actually be mutli-level-push-menu-specific, but I've been banging my head against it for awhile and I'm not having any luck, so I'm hoping you might be able to point me in the right direction. Let's start with this fiddle...

http://jsfiddle.net/graycarper/W6nrX/8/

You'll see that I have a menu with many leaf nodes under the first three groupings (Venues, Departments, Types), but you can't scroll down to see all the leaf nodes because I've set overflow on body and html to 'hidden'. What I'd like to achieve is a scrollbar that's flush against the right side of the menu which will allow me to see all the menu leaves without scrolling the entire document. You'll see one of my attempts at doing this (by bounding the #menu with a fixed height and setting overlap-y to 'auto'), but that's not been effective, and I'm wondering if it's because of the various layers that the menu has.

At any rate, any help you can provide would be wonderful. Thanks so much!

-Gray

**Comment by adgsm** [comment]
solution using iscroll; take a look at #107
