### ISSUE TITLE
Strange Load Flicker

### ISSUE THREAD

**Issue by jagarrett** [adgsm/multi-level-push-menu#98]
I'm loving the menu, but I have one small issue.  During the page load the elements of the menu are visible for an instant until the page fully loads.  I've tried moving the JavaScript to different places with no result.  I'm using ASP.Net with Web Forms.  The menu markup is in user controls.  I've tried the javascript in the Master Page, .aspx page and the user control.  Any Ideas?

**Comment by adgsm** [comment]
Please take a look at the solution proposed for issue #7.
